FROM virgiletn/docker-ros:kinetic-core
LABEL maintainer "virgile.dauge@telecomnancy.net"

# nvidia-docker hooks
LABEL com.nvidia.volumes.needed="nvidia_driver"
ENV PATH /usr/local/nvidia/bin:${PATH}
ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64:${LD_LIBRARY_PATH}
ENV LIBGL_ALWAYS_INDIRECT 0

#Installing all required dependencies according to the source cloned before
RUN apt-get -qq update \
    && apt-get install -y \
      apt-utils \
      ros-kinetic-rviz \
    && rm -rf /var/lib/apt/lists/*

# IMPORTANT: Update these values to your primary computer user id and group id
# On OSX use `id -u` and `id -g` to find the correct values
ENV uid 1000
ENV gid 1000
RUN export uid=${uid} gid=${gid} \
      &&  mkdir -p /ros \
      &&  echo "ros:x:${uid}:${gid}:ros,,,:/ros:/bin/bash" >> /etc/passwd \
      &&  echo "ros:x:${uid}:" >> /etc/group \
      &&  echo "ros ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/ros \
      &&  chmod 0440 /etc/sudoers.d/ros \
      &&  chown ${uid}:${gid} -R /home/ros
