FROM virgiletn/docker-ros:melodic-core
LABEL maintainer "virgile.dauge@telecomnancy.net"

# install compilation tools
RUN apt-get update \
    && apt-get install -y \
      apt-utils \
      build-essential \
      g++ \
&& rm -rf /var/lib/apt/lists/*

SHELL ["bin/bash", "-c"]
# add environment setup
RUN echo 'source /opt/ros/melodic/setup.bash' >> .bashrc

# Setup catkin workspace
RUN source /opt/ros/melodic/setup.bash \
                  && mkdir -p /home/catkin_ws/src \
                  && cd /home/catkin_ws/src \
                  && catkin_init_workspace \
                  && cd /home/catkin_ws/ \
                  && catkin_make \
                  && echo 'source /home/catkin_ws/devel/setup.bash' >> /.bashrc
