FROM virgiletn/docker-ros:kinetic-core
LABEL maintainer "virgile.dauge@inria.fr"

#Changing default shell for multi commands
SHELL ["bin/bash", "-c"]

# install compilation tools
RUN apt-get update \
    && apt-get install -y \
      apt-utils \
      build-essential \
      g++ \
&& rm -rf /var/lib/apt/lists/*

# Setup catkin workspace
RUN source /opt/ros/kinetic/setup.bash \
                  && mkdir -p /home/catkin_ws/src \
                  && cd /home/catkin_ws/src \
                  && catkin_init_workspace \
                  && cd /home/catkin_ws/ \
                  && catkin_make

#Sourcing new workspace
RUN echo 'source /home/catkin_ws/devel/setup.bash' >> /.bashrc
