FROM virgiletn/docker-ros:kinetic-catkin-ws
LABEL maintainer "virgile.dauge@inria.fr"

#Changing default shell for multi commands
SHELL ["bin/bash", "-c"]

#Installing rviz and intel graphics drivers
RUN apt-get -qq update \
    && apt-get install -y \
      ros-kinetic-rviz \
      libgl1-mesa-glx  \
      libgl1-mesa-dri  \
    && rm -rf /var/lib/apt/lists/*

#Adding rviz conig from github repo.
#Should CHANGE THIS ASAP, maybe clonning a repo with all configs ?
ADD https://raw.githubusercontent.com/virgileTN/docker-ros/master/rviz-intel/configs/vlp16.rviz /home/

#Launching rviz
CMD ["rosrun", "rviz", "rviz"]
