FROM virgiletn/docker-ros:kinetic-core
LABEL maintainer "virgile.dauge@telecomnancy.net"

#Installing all required dependencies according to the source cloned before
RUN apt-get -qq update \
        && apt-get install -y \
        ros-kinetic-rviz \
        libgl1-mesa-glx  \
        libgl1-mesa-dri  \
        && rm -rf /var/lib/apt/lists/*

#Changing default shell for multi commands
SHELL ["bin/bash", "-c"]

#Launching rviz
CMD source /opt/ros/kinetic/setup.bash \
        && rosrun rviz rviz
