FROM virgiletn/docker-ros:kinetic-catkin-ws
LABEL maintainer "virgile.dauge@inria.fr"

#Clonning velodyne repository (getting last version)
RUN git clone \
        https://github.com/laboshinl/loam_velodyne.git \
        /home/catkin_ws/src/loam_velodyne

#Installing all required dependencies according to the source cloned before
RUN apt-get -qq update \
        && apt-get install -y \
        # software-properties-common \
        # python-software-properties \
        sudo \
        apt-utils \
        ros-kinetic-rviz \
        ros-kinetic-perception-pcl\
        ros-kinetic-pcl-ros \
        libopenni2 \
        libgl1-mesa-glx  \
        libgl1-mesa-dri  \
        && rosdep install --as-root apt:yes -r --from-paths /home/catkin_ws/ --ignore-src --rosdistro kinetic -y \
        && rm -rf /var/lib/apt/lists/*

# RUN add-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl \
#         && apt-get -qq update \
#         && apt-get install -y \
#         libpcl-all \
#         && rm -rf /var/lib/apt/lists/*
#Changing default shell for multi commands
SHELL ["bin/bash", "-c"]

#Compiling cloned sources
RUN source /opt/ros/kinetic/setup.bash \
        && cd /home/catkin_ws/ \
        && catkin_make

#Default command launching the node
CMD cd /home/catkin_ws \
        && source devel/setup.bash \
&& roslaunch loam_velodyne loam_velodyne.launch
