FROM virgiletn/docker-ros:kinetic-catkin-ws
LABEL maintainer "virgile.dauge@inria.fr"

#Clonning velodyne repository (getting last version)
RUN git clone \
        https://github.com/laboshinl/loam_velodyne.git

#Installing all required dependencies according to the source cloned before
RUN apt-get -qq update \
        && apt-get install -y \
        sudo \
        && rosdep install --as-root apt:yes -r --from-paths /home/catkin_ws/ --ignore-src --rosdistro kinetic -y \
        && rm -rf /var/lib/apt/lists/*

#Changing default shell for multi commands
SHELL ["bin/bash", "-c"]

#Compiling cloned sources
RUN source /opt/ros/kinetic/setup.bash \
        && cd /home/catkin_ws/ \
        && catkin_make

#Default command launching the node
CMD cd /home/catkin_ws \
        && source devel/setup.bash \
&& roslaunch loam_velodyne loam_velodyne.launch
